# Generated by Django 3.0.5 on 2020-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_schedule_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synctask',
            name='action',
            field=models.SmallIntegerField(choices=[(3, 'update'), (1, 'create'), (2, 'get'), (0, 'list')]),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'sent'), (0, 'archive'), (1, 'pending')], default=1),
        ),
    ]
