# Generated by Django 3.0.5 on 2020-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_schedule_job', '0002_auto_20200421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synctask',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'create'), (3, 'update'), (2, 'get'), (0, 'list')]),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
