# Generated by Django 3.0.5 on 2020-04-17 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('system_log_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'archive'), (1, 'active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'f_system_log',
            },
        ),
    ]
