# Generated by Django 3.0.5 on 2020-04-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_system_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (0, 'archive')], default=1),
        ),
    ]
