# Generated by Django 3.0.6 on 2020-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_social_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(),
        ),
    ]
