# Generated by Django 3.2.9 on 2021-12-03 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheckExpiredTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Email Check Expired Time',
                'db_table': 'email_check_expired_time',
            },
        ),
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Sending'), (2, 'Completed'), (3, 'Fail'), (4, 'Skip')], default=0)),
                ('params', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('count', models.SmallIntegerField(default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Email Task',
                'db_table': 'email_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
