# Generated by Django 3.0.5 on 2020-04-26 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents')),
            ],
            options={
                'db_table': 'f_file',
            },
        ),
    ]
