# Generated by Django 3.0.5 on 2020-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (0, 'inactive')], default=0),
        ),
    ]
