# Generated by Django 3.0.5 on 2020-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0002_auto_20200505_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
    ]
