# Generated by Django 3.0.5 on 2020-04-17 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0002_auto_20200416_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'approved'), (4, 'archive'), (2, 'rejected'), (3, 'sent email'), (0, 'pending')], default=0)),
            ],
            options={
                'db_table': 'a_application',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
    ]
