# Generated by Django 3.0.5 on 2020-04-21 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0004_auto_20200417_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'approved'), (4, 'sent email'), (3, 'rejected'), (1, 'pending'), (0, 'archive')], default=1),
        ),
    ]
