# Generated by Django 3.0.5 on 2020-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0005_auto_20200421_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email_status',
            field=models.SmallIntegerField(choices=[(0, 'not send email'), (1, 'sent email')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(4, 'rejected'), (3, 'approved'), (1, 'wait to sync'), (0, 'archive'), (2, 'wait to review')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
    ]
