# Generated by Django 3.0.5 on 2020-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0006_auto_20200421_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email_status',
            field=models.SmallIntegerField(choices=[(1, 'sent email'), (0, 'not send email')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'wait to sync'), (2, 'wait to review'), (4, 'rejected'), (0, 'archive'), (3, 'approved')], default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (0, 'inactive')], default=0),
        ),
    ]
