# Generated by Django 3.0.5 on 2020-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0007_auto_20200421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email_status',
            field=models.SmallIntegerField(choices=[(0, 'not send email'), (1, 'sent email')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'wait to review'), (0, 'archive'), (3, 'approved'), (1, 'wait to sync'), (4, 'rejected')], default=1),
        ),
    ]
