# Generated by Django 3.0.6 on 2020-05-11 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTableLet',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=100)),
                ('let', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'f_sj_sync_table_let',
            },
        ),
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('sync_task_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(2, 'sent'), (1, 'pending'), (0, 'archive')], default=1)),
                ('category', models.SmallIntegerField(choices=[(1, 'product'), (0, 'application')])),
                ('action', models.SmallIntegerField(choices=[(0, 'list'), (2, 'get'), (3, 'update'), (1, 'create')])),
                ('parameters', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'f_sj_sync_task',
            },
        ),
    ]
