# Generated by Django 3.0.6 on 2020-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_schedule_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synctask',
            name='action',
            field=models.SmallIntegerField(choices=[(3, 'update'), (0, 'list'), (2, 'get'), (1, 'create')]),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'application'), (1, 'product')]),
        ),
        migrations.AlterField(
            model_name='synctask',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'archive'), (2, 'sent'), (1, 'pending')], default=1),
        ),
    ]
